### ISSUE TITLE
improving user experience with Clang/LLD in GCC mode

### ISSUE THREAD

**Issue by Andarwinux** [mstorsjo/msvc-wine#129]

**Comment by mstorsjo** [comment]
Indeed, using Clang in MSVC mode with the GCC style command line interface does have some sorts of limitations like these. Some options have been added over time, like `-fms-runtime-lib=` which allow doing the same as `-MT`/`-MD`/`-MTd`/`-MDd` in the cl.exe style interface, so it's not implausible to add GCC style options for more MSVC specifics either. (Althoug using something like `msvcenv-native.sh` to set up the environment also works.)

In any case, I feel this issue is out of scope for the msvc-wine project, feel free to file issues at https://github.com/llvm/llvm-project/issues for things you feel should be added in Clang.
