### ISSUE TITLE
Clang: standard libraries not found

### ISSUE THREAD

**Issue by noughtmare** [mstorsjo/msvc-wine#56]
When trying the "Use with Clang/LLD in MSVC mode" approach, I'm getting warnings and errors like this:

```
clang-14: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
test.cpp(1,10): fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

I'm guessing that `msvc-not-found` warning is related to the error, because clang might get these standard library files from the visual studio installation.

Are the standard libraries like `iostream` supposed to be provided by msvc or do I have to use mingw's libraries?

**Comment by mstorsjo** [comment]
> When trying the "Use with Clang/LLD in MSVC mode" approach, I'm getting warnings and errors like this:
> 
> ```
> clang-14: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
> test.cpp(1,10): fatal error: 'iostream' file not found
> #include <iostream>
>          ^~~~~~~~~~
> 1 error generated.
> ```
> 
> I'm guessing that `msvc-not-found` warning is related to the error, because clang might get these standard library files from the visual studio installation.
> 
> Are the standard libraries like `iostream` supposed to be provided by msvc or do I have to use mingw's libraries?

When using Clang/LLD in MSVC mode, almost all the headers that you'd be using are provided by MSVC/WinSDK - the only headers that Clang itself provides are headers for compiler internals/intrinsics.

You get the warning about unable to find the Visual Studio installation, because it's trying to use `link.exe` for linking (and Clang has got some extra custom logic for finding that binary); the examples in https://github.com/mstorsjo/msvc-wine#use-with-clanglld-in-msvc-mode either do linking by invoking `lld-link` (instead of `link`) manually on built object files, or by passing `-fuse-ld=lld` if having `clang` run the linker.

Then secondly, about `<iostream>` not being found - Clang checks the environment variable `INCLUDE` for implicit include directories. If you follow the example in the readme, the command `BIN=~/my_msvc/bin/x64 . ./msvcenv-native.sh` will set up the environment variables `INCLUDE` and `LIB` - which should be enoug for finding includes like `<iostream>`.

Alternatively, instead of using the environment variables, you can also pass the option `-winsysroot` to `clang-cl`, which makes it locate all those bits based on that directory - see https://github.com/mstorsjo/msvc-wine/commit/2d2d7db0b55b0f061eca5f4f1c149608d5501ec6 for an example on using that.

**Comment by noughtmare** [comment]
Thanks for  the quick response.

I have followed the readme and can confirm that the $LIB and $INCLUDE variables are set properly, but the command

```
clang --target=x86_64-windows-msvc test.cpp -o test.exe -fuse-ld=lld
```

And the alternative:

```
clang-cl --target=x86_64-windows-msvc test.cpp -Fetest-x86_64.exe -winsysroot /path/to/my_msvc/ -fuse-ld=lld
```

Both still give that iostream not found error.

**Comment by mstorsjo** [comment]
Can you provide the output of `echo $INCLUDE`, and rerun the failing clang invocations with `-v` added (which should print out which paths it tried using as include paths)?

**Comment by noughtmare** [comment]
I'm running NixOS so the clang executable is in a bit of a nonstandard place.

This is the full output:

```
msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ echo $INCLUDE
/home/user/my_msvc/vc/tools/msvc/14.34.31933/include;/home/user/my_msvc/kits/10/include/10.0.22621.0/shared;/home/user/my_msvc/kits/10/include/10.0.22621.0/ucrt;/home/user/my_msvc/kits/10/include/10.0.22621.0/um;/home/user/my_msvc/kits/10/include/10.0.22621.0/winrt

msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ echo $LIB
/home/user/my_msvc/vc/tools/msvc/14.34.31933/lib/x64;/home/user/my_msvc/kits/10/lib/10.0.22621.0/ucrt/x64;/home/user/my_msvc/kits/10/lib/10.0.22621.0/um/x64

msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ clang --target=x86_64-windows-msvc test.cpp -o test.exe -fuse-ld=lld -v
clang version 14.0.6
Target: x86_64-unknown-windows-msvc
Thread model: posix
InstalledDir: /usr/bin
 "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/bin/clang-14" -cc1 -triple x86_64-unknown-windows-msvc19.20.0 -emit-obj -mrelax-all -mincremental-linker-compatible --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -v -fcoverage-compilation-dir=/home/user/msvc-wine/test -nostdsysteminc -resource-dir /nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6 -internal-isystem /nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include -fdeprecated-macro -fdebug-compilation-dir=/home/user/msvc-wine/test -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.20 -std=c++14 -fdelayed-template-parsing -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o /run/user/1000/test-230d4a.o -x c++ test.cpp
clang -cc1 version 14.0.6 based upon LLVM 14.0.6 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include"
#include "..." search starts here:
End of search list.
test.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.

msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ clang-cl --target=x86_64-windows-msvc test.cpp -Fetest-x86_64.exe -winsysroot /home/user/my_msvc/ -fuse-ld=lld -v
clang version 14.0.6
Target: x86_64-unknown-windows-msvc
Thread model: posix
InstalledDir: /usr/bin
 "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/bin/clang-14" -cc1 -triple x86_64-unknown-windows-msvc19.20.0 -emit-obj -mrelax-all -mincremental-linker-compatible --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -mllvm -x86-asm-syntax=intel -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -D_MT -flto-visibility-public-std --dependent-lib=libcmt --dependent-lib=oldnames -stack-protector 2 -fms-volatile -fdiagnostics-format msvc -v -fcoverage-compilation-dir=/home/user/msvc-wine/test -nostdsysteminc -resource-dir /nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6 -internal-isystem /nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include -internal-isystem "/home/user/my_msvc/DIA SDK/include" -fdeprecated-macro -fdebug-compilation-dir=/home/user/msvc-wine/test -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.20 -std=c++14 -fdelayed-template-parsing -fcolor-diagnostics -faddrsig -o /run/user/1000/test-f4de66.obj -x c++ test.cpp
clang -cc1 version 14.0.6 based upon LLVM 14.0.6 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/user/my_msvc/DIA SDK/include
End of search list.
test.cpp(1,10): fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

**Comment by noughtmare** [comment]
Hmm... That `/home/user/my_msvc/DIA SDK/include` directory only contains this:

```
$ ls "/home/user/my_msvc/DIA SDK/include"
cvconst.h  dia2.h  diacreate.h
```

**Comment by mstorsjo** [comment]
> I'm running NixOS so the clang executable is in a bit of a nonstandard place.

Hmm. Having the executable in a nonstandard place should be entirely fine here - but is the NixOS Clang somehow patched and/or built with specific uncommon defaults? Does it behave differently if you try using an upstream release binary of Clang (from e.g. https://github.com/llvm/llvm-project/releases) instead of the NixOS provided one?

> This is the full output:
> 
> ```
> msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ echo $INCLUDE
> /home/user/my_msvc/vc/tools/msvc/14.34.31933/include;/home/user/my_msvc/kits/10/include/10.0.22621.0/shared;/home/user/my_msvc/kits/10/include/10.0.22621.0/ucrt;/home/user/my_msvc/kits/10/include/10.0.22621.0/um;/home/user/my_msvc/kits/10/include/10.0.22621.0/winrt
> 
> msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ echo $LIB
> /home/user/my_msvc/vc/tools/msvc/14.34.31933/lib/x64;/home/user/my_msvc/kits/10/lib/10.0.22621.0/ucrt/x64;/home/user/my_msvc/kits/10/lib/10.0.22621.0/um/x64
> ```

These seem correct to me - I presume that the listed directories do exist and contain the expected headers?

What if you redefine these variables to be separated by `:` instead of `;` - does that help? As these variables are specific to the MSVC usecase, the convention so far has been to keep them separated with `;` like on Windows - but does NixOS maybe patch Clang to switch the splitting to use `:` like for other path variables on Unix?

> ```
> msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ clang --target=x86_64-windows-msvc test.cpp -o test.exe -fuse-ld=lld -v
> ignoring nonexistent directory "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include"
> #include "..." search starts here:
> End of search list.
> ```

Apparently this one didn't pick up on `$INCLUDE` at all. I wonder if this is a difference in the NixOS provided binary (or maybe some wrapping of it?) which makes it ignore environment variables?


> ```
> msvc-clang-chrootenv:user@nixos-laptop:~/msvc-wine/test$ clang-cl --target=x86_64-windows-msvc test.cpp -Fetest-x86_64.exe -winsysroot /home/user/my_msvc/ -fuse-ld=lld -v
> ignoring nonexistent directory "/nix/store/jdkdm7arb5rqw2cy1lbbfqrar5k9db9y-clang-14.0.6/lib/clang/14.0.6/include"
> #include "..." search starts here:
> #include <...> search starts here:
>  /home/user/my_msvc/DIA SDK/include
> End of search list.
> ```

Now this is even weirder, because it did take the `-winsysroot` option into account, but it didn't find the other `vc/tools/msvc` directories, only the `DIA SDK` ones. Using this option requires your MSVC installation to be done with https://github.com/mstorsjo/msvc-wine/commit/f4f04810530e2b54677ee7d84ce35497ace45b46 which keeps upper/mixed case symlinks for the `VC/Tools/MSVC` directories though - do you have them in your MSVC installation?



> > ```
> > #include <...> search starts here:
> >  /home/user/my_msvc/DIA SDK/include
> > ```
> 
> 
> Hmm... That `/home/user/my_msvc/DIA SDK/include` directory only contains this:
> 
> 
> ```
> $ ls "/home/user/my_msvc/DIA SDK/include"
> cvconst.h  dia2.h  diacreate.h
> ```


Yes, this is a minor auxillary SDK, it's only supposed to have these files. It's supposed to pick up all the directories from `$INCLUDE` which does contain the bulk of the includes.

**Comment by noughtmare** [comment]
It does work with the standard clang distribution. So this is really a problem with NixOS. I'll continue asking them how to properly pass these include and library directories. Thanks for pointing me in the right direction!

**Comment by noughtmare** [comment]
If anybody else stumbles upon this looking to make it work on NixOS. For me the NixOS provided clang also works if you set these environment variables instead of LIB and INCLUDE:

```
$ export NIX_CFLAGS_COMPILE="-I/home/user/my_msvc/vc/tools/msvc/14.34.31933/include -I/home/user/my_msvc/kits/10/include/10.0.22621.0/shared -I/home/user/my_msvc/kits/10/include/10.0.22621.0/ucrt -I/home/user/my_msvc/kits/10/include/10.0.22621.0/um -I/home/user/my_msvc/kits/10/include/10.0.22621.0/winrt"

$ export NIX_LDFLAGS="-L/home/user/my_msvc/vc/tools/msvc/14.34.31933/lib/x64 -L/home/user/my_msvc/kits/10/lib/10.0.22621.0/ucrt/x64 -L/home/user/my_msvc/kits/10/lib/10.0.22621.0/um/x64"
```

**Comment by darealshinji** [comment]
I ran into the same issue. The solution for me was to append the architecture `x64` to `BIN`:
` BIN=~/opt/msvc/bin/x64 . ./msvcenv-native.sh`

But now clang refuses to use lld for linking:
```
$ clang-cl test/hello.c -out:hello.exe
/usr/bin/ld: Error: unable to disambiguate: -nologo (did you mean --nologo ?)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
$ which lld-link
/home/djcj/bin/lld-link
$ which clang-cl
/home/djcj/bin/clang-cl
```

**Comment by mstorsjo** [comment]
> I ran into the same issue. The solution for me was to append the architecture `x64` to `BIN`: ` BIN=~/opt/msvc/bin/x64 . ./msvcenv-native.sh`
> 
> But now clang refuses to use lld for linking:
> 
> ```
> $ clang-cl test/hello.c -out:hello.exe
> /usr/bin/ld: Error: unable to disambiguate: -nologo (did you mean --nologo ?)
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> $ which lld-link
> /home/djcj/bin/lld-link
> $ which clang-cl
> /home/djcj/bin/clang-cl
> ```

That seems weird - clang-cl shouldn't try to use `/usr/bin/ld` to link. But perhaps it does in some odd combination of cases?

Linking with clang-cl like that does default to using `link.exe` (which would need using the whole msvc-wine wrapping), and that's probably not available here - maybe that's what causes it to try defaulting to `ld` instead? To make clang-cl use `lld-link` instead of `link.exe`, you need to pass `-fuse-ld=lld` to the `clang-cl` command.

**Comment by darealshinji** [comment]
Passing `-fuse-ld=lld` works, thanks. Can you add this info to the README?

**Comment by mstorsjo** [comment]
> Passing `-fuse-ld=lld` works, thanks. Can you add this info to the README?

This is already somewhat suggested with the examples at https://github.com/mstorsjo/msvc-wine#use-with-clanglld-in-msvc-mode, where I'm either linking separately by invoking `lld-link` manually or passing `-fuse-ld=lld` to the `clang` command. But I guess we could make it even clearer. I guess https://github.com/mstorsjo/msvc-wine/commit/clang-cl-link would make it even clearer?

FWIW I did test your scenario, linking with `clang-cl` without having `link.exe` in `$PATH`, and I'm not getting that confusing error you got, but instead get a much clearer call to action:
```
clang-cl: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
clang-cl: error: unable to execute command: Executable "link.exe" doesn't exist!
clang-cl: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm getting this with as old versions as Clang 12 at least, and with the latest nightly. But I guess you might end up with what you had, if your clang is built with a distro provided Clang which is built with `CLANG_DEFAULT_LINKER` set?

**Comment by darealshinji** [comment]
I'm using clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz from here:
https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0

**Comment by mstorsjo** [comment]
> I'm using clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz from here:
> https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0

That's strange - even with that, I'm still getting the same error about `link.exe` not existing.

Anyway - does the suggested documentation improvement look good to you?
